# Generated by Django 4.1.2 on 2022-12-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("stock", models.CharField(max_length=255, null=True)),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.FloatField(default=0.0)),
            ],
        ),
    ]
